# Generated by Django 4.2.26 on 2026-01-12 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('fasting_goal_hours', models.FloatField(default=16.0, verbose_name='Meta de Jejum (horas)')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='FastingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Início')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Fim')),
                ('duration_hours', models.FloatField(blank=True, null=True, verbose_name='Duração (horas)')),
                ('fasting_type', models.CharField(choices=[('intermittent', 'Jejum Intermitente'), ('extended', 'Jejum Prolongado'), ('other', 'Outro')], default='intermittent', max_length=20, verbose_name='Tipo de Jejum')),
                ('energy_level', models.IntegerField(blank=True, choices=[(1, 'Baixo'), (2, 'Médio'), (3, 'Alto')], null=True, verbose_name='Nível de Energia')),
                ('focus_level', models.IntegerField(blank=True, choices=[(1, 'Baixo'), (2, 'Médio'), (3, 'Alto')], null=True, verbose_name='Nível de Foco')),
                ('mood_level', models.IntegerField(blank=True, choices=[(1, 'Baixo'), (2, 'Médio'), (3, 'Alto')], null=True, verbose_name='Nível de Humor')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fasting_records', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Registro de Jejum',
                'verbose_name_plural': 'Registros de Jejum',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(verbose_name='Peso (kg)')),
                ('reference_month', models.CharField(max_length=7, verbose_name='Mês de Referência')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_records', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Registro de Peso',
                'verbose_name_plural': 'Registros de Peso',
                'ordering': ['-reference_month'],
                'unique_together': {('user', 'reference_month')},
            },
        ),
    ]
